@startuml
class AAUOC{
    newLocation(l: Location): void
    newEvent(e: Event): void
    newPerson(p: Person): void
    informEvent(e: Event): void
    register(m: Member, e: Event): void
}
class Location{
    description: String
    address: String
}
class Person{
    name: String
}
class Member{
    e-mail: String
}
class BoardMember{}
class Event{
    date: Date
    description: String
    assign(l:Location): void
}
class Conference{
    max-attendees: Integer
}
class BoardMeeting{}


AAUOC o-- "0..*" Location
AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Member "0..*" -- "0..*" Event : attendsTo
Location "1" -- "0..*" Event : isLocatedIn
Person "0..*" -- "0..*" Conference: attendsTo
BoardMeeting "0..*" -- "0..*" BoardMember : attendsTo


@enduml