@startuml
class AAUOC{
}
class Location{
}
class Person{
}
class Event{}
class Conference{}
class BoardMeeting{}
class Member{}
class BoardMember{}

AAUOC o-- Location
AAUOC o-- Event
AAUOC o-- Person

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

Location --Event
Person -- Conference
BoardMeeting -- BoardMember

@enduml